### ISSUE TITLE
3.0.3 QPKG Fails to Install

### ISSUE THREAD

**Issue by LesFromIL** [kenstir/pytivo#2]
QNAP TS212 NAS reports "pyTivo 3.0.3 installation failed. The following QPKG must be installed and enabled: Python >= 2.7." I followed the install instructions. Python IS installed.
Response to "which python" is "/opt/bin/python".
Response to "python -V" is "Python 2.7.13".
So what is wrong? QNAP NAS Firmware is 4.3.3.0361.

**Comment by kenstir** [comment]
Hi LesFromIL, I suspect that is a bug in the packaging, and it is requiring the QNAP packed version of Python; you definitely have the Entware-ng version.  Just for now try installing the Python from the QNAP app center before installing pyTivo.  When it runs, the pyTivo script looks for /opt/bin/python first, so this is just to get past the install step.

**Comment by LesFromIL** [comment]
Thanks for the response. Just before I got your response, that is pretty much what I did,
I first uninstalled the Entware-ng package, then I installed the QNAP Python 2,7 pkg, re-installed the Entware-ng pkg and finally got a successful install of pyTivo 3.0.3. BTW, don't know if this helps, but I had the same problem when I built the 3.0.3 pkg myself (via QDK). Do you think this is a QNAP pkg installer issue? If so, should the problem be addressed to QNAP?
Thanks,
Les

**Comment by kenstir** [comment]
Glad you got it installed!  No, I don't think it's a QNAP issue, I think it's because of this line in the qpkg.cfg file:

> QPKG_REQUIRE="Python >= 2.7, Entware-ng"

When I have a few minutes I will try out making a release that requires either Entware-ng or Python >= 2.7.  I think that would be:

> QPKG_REQUIRE="Python >= 2.7 | Entware-ng"

**Comment by LesFromIL** [comment]
So, for lack of anywhere else to find an answer to a pyTivo issue I will
try replying to your original email to me, however, this is on a completely
different issue.
I setup the .conf file to share Pictures, Video and Music to the S4
Premier. Pictures and Video shares work fine but Music share wont play any
mp3 files. I get the error about the server being down. I can see all of
the folders/files, but when I click Play I get the error.

A problem occurred while accessing the server. This may
be a temporary problem due to a network interruption or
the server is being busy. If the problem persists check your
network connections and verify that the Tivo Server
application is running on your computer.

Any thoughts on why this is happening?
Thanks,
Les B.

**Comment by kenstir** [comment]
@LesFromIL First I would look at the log files.  QNAP-pytivo leaves a debug-level log file in /share/CACHEDEV1_DATA/.qpkg/pyTivo/debug.log (your install dir may differ and can be found with the command `getcfg pyTivo Install_Path -f /etc/config/qpkg.conf`).

**Comment by kenstir** [comment]
Fixed in 8c219755dd519676ae3218d3a061043568395b15
